#!/bin/bash

# Run scheduler server inside docker container
export NDSCHEDULER_SETTINGS_MODULE=simple_scheduler.settings && \
/usr/local/bin/python /app/src/ndscheduler/simple_scheduler/scheduler.py

